apiVersion: v1
kind: apiVersion: v1
kind: Pod
metadata:
  name: primeiro-pod-declativo
spec:
  containers:
  - name: nginx-conteiner
    image: nginx-conteiner
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: <Port>
