- hosts: terraform-ansible
  tasks:
    - name: Instalando Depedências Python
      apt:
        pkg: 
          - python3
          - virtualenv
        update_cache: yes
      become: yes 
    - name: Git Clone
      ansible.builtin.git:
        repo: https://github.com/guilhermeonrails/clientes-leo-api.git
        dest: /home/ubuntu/tcc
        version: master
    - name: Instalando Depedências com PIP
      pip:
        virtualenv: /home/ubuntu/tcc/venv
        name:
          - django 
          - djangorestframework
    #- name: Verificação do Projeto
    #  stat:
    #    path: /home/ubuntu/tcc/setup/settings.py
    #  register: projeto 
    #- name: Iniciando Projeto
    #  shell: '. /home/ubuntu/tcc/venv/bin/activate; django-admin startproject setup /home/ubuntu/tcc'
    #  when: not projeto.stat.exists
    - name: Alteração arquivo hosts 
      lineinfile: 
        path: /home/ubuntu/tcc/setup/settings.py
        regexp: 'ALLOWED_HOSTS'
        line: 'ALLOWED_HOSTS = ["*"]'
        backrefs: yes 
