- hosts: terraform-ansible
  tasks:
    - name: Instalando Depedências Python
      apt:
        pkg: 
          - python3
          - virtualenv
        update_cache: yes
      become: yes 
    - name: Instalando Depedências com PIP
      pip:
        virtualenv: /home/ubuntu/tcc/venv
        name:
          - django 
          - djangorestframework
    
